name: Issue Email Checker

on:
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled]

jobs:
  email-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: weekdaycare/Issue-email-checker@v1.0
        with:
          issue_state: open
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: prepare worktree
        run: |
          git fetch origin output
          git worktree add output output

      - name: mv subscribe.json
        run: |
          mkdir -p output/v2
          cp subscribe.json output/v2/subscribe.json

      - name: push commit
        run: |
          cd output
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add v2/subscribe.json
          git commit -m "Update subscribe.json [bot]" || echo "No changes to commit"
          git push origin HEAD:output