name: Issue Email Checker

on:
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled]

jobs:
  email-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout output branch
        uses: actions/checkout@v4
        with:
          ref: output

      - uses: weekdaycare/Issue-email-checker@main
        with:
          issue_state: open
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Switch to output branch and update file
        run: |
          mkdir -p v2
          cp subscribe.json v2/subscribe.json
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add v2/subscribe.json
          git commit -m "Update subscribe.json [bot]" || echo "No changes to commit"
          git push origin HEAD:output